baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Mirror Software"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Mirror Software"
  description: "We specialize in providing custom software services in data engineering, machine learning and API development."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "spiegel.karl@gmail.com"

  # contact:
  #   - "spiegel.karl@gmail.com"

  copyright: "© 2022 Mirror Software All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
